basicE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path


from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category_detail'),
    path('cart/>', views.cart, name='cart'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

from djmoney.models.fields import MoneyField


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=256)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank = True, default = None)

    def __str__(self):
        return self.name

    def get_parents(self):
        l = [self]
        while l[-1].parent is not None:
            l.append(l[-1].parent)
        return l[::-1]


class Product(models.Model):
    name = models.CharField(max_length=256)
    price = MoneyField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.name



class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.pk)+" : "+str(self.user)+' : '+str(self.date)

class OrderedProducts(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    price = MoneyField(max_digits=10, decimal_places=2, null=True)
    class Meta:
        unique_together = (("order", "product"),)

shop/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

import json

from .models import Product, Category, Order, OrderedProducts

class ProductListView(generic.ListView):
    template_name = 'shop/products.html'
    model = Product

class ProductDetailView(generic.DetailView):
    template_name = 'shop/product_detail.html'
    model = Product

class CategoryListView(generic.ListView):
    template_name = 'shop/category.html'
    model = Category

class CategoryDetailView(generic.DetailView):
    template_name = 'shop/category_detail.html'
    model = Category

class OrderListView(generic.ListView, LoginRequiredMixin):
    template_name = 'shop/orders.html'
    model = Order
    def get_queryset(self):
        qs = Order.objects.filter(user=self.request.user.pk)
        return qs

class OrderDetailView(generic.DetailView, LoginRequiredMixin):
    template_name = 'shop/order_detail.html'
    model = Order
    def get_queryset(self):
        qs = Order.objects.filter(user=self.request.user.pk)
        return qs

@login_required
def cart(request):
    cookies = json.loads(request.COOKIES.get('cart',"{}"))
    
    if request.method == "GET":
        context = {}
        context['objects'] = [{'p':Product.objects.get(pk=i),
                                'q':cookies[i]} 
                                for i in cookies.keys()]

        return render(request, "shop/cart.html", context)
    elif request.method == "POST":
        o = Order(user=User.objects.get(pk=request.user.pk))
        o.save()
        for i in cookies:
            product=Product.objects.get(pk=i)
            quantity=cookies[i]
            price=product.price
            p = OrderedProducts(order=o,
                              product=product,
                              quantity=quantity,
                              price=price)
            p.save()
        res = HttpResponseRedirect(reverse('shop:orders'))
        res.delete_cookie('cart')
        return res

def index(request):
    return render(request, 'shop/index.html')

shop/templates/shop/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Some Shop</title>{% endblock %}
  <meta charset="utf-8">
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0/dist/js.cookie.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="{%static 'js/index.js'%}"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'shop:index' %}">Home</a></li>
          <li><a href="{% url 'shop:products' %}">Products</a></li>
          <li><a href="{% url 'shop:category' %}">Categories</a></li>
          
          {% if user.is_authenticated %}
          <li>Hello {{ user }}</li>
          <li><a href="{% url 'shop:cart' %}">Cart<b id="cart"></b></a></li>
          <li><a href="{% url 'shop:orders' %}">Orders<b id="cart"></b></a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-50 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

shop/templates/shop/cart.html
{% extends "shop/base_generic.html" %}

{% block content %}

<h1>Cart</h1>
<ul class='data-list'>
{% for o in objects %}
    <li>
        <a href="{% url 'shop:product_detail' o.p.pk %}">{{ o.p.name | title}}</a> 
        - {{ o.p.price }} Qty. {{o.q}}
    </li>
{% empty %}
    <li>Your cart is empty</li>
{% endfor %}
</ul>
{% if objects %}
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Place Order">
</form>
{% endif %}

{% endblock %}

shop/templates/shop/category.html
{% extends "shop/base_generic.html" %}

{% block content %}

<h1>Categories</h1>
<ul class='data-list'>
{% for cat in object_list %}
    <li>
        <a href="{% url 'shop:category_detail' cat.pk %}">{{ cat.name}}</a> 
    </li>
{% empty %}
    <li>No categories... Weird huh?</li>
{% endfor %}
</ul>

{% endblock %}

shop/templates/shop/category_detail.html
{% extends "shop/base_generic.html" %}

{% block content %}
<div id="path">
<a href="{%url 'shop:index'%}"> Home </a>
{% for cat in category.get_parents %}
> <a href="{% url 'shop:category_detail' cat.pk %}">{{cat}}</a>
{% endfor %}
</div>
<h1 id="name">{{category.name | title}}</h1>
<div id="children">
    Sub-categories: 
{% for child in category.category_set.all %}
<a href="{% url 'shop:category_detail' child.pk %}"> {{ child }} </a>
{%empty%}
None
{% endfor %}
</div>
<br>
<ul class='data-list'>
{% for product in category.product_set.all %}
<li>
    <a href="{% url 'shop:product_detail' product.pk %}">{{ product.name | title}}</a> 
        - {{ product.price }}
</li>
{% endfor %}
</ul>

{% endblock %}

shop/templates/shop/index.html
{% extends "shop/base_generic.html" %}

{% block content %}
  <h1>The Shop</h1>
  <p>This is a shop</p>
  <!-- <h2>Stats:</h2>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Students:</strong> {{ num_students }}</li>
  </ul> -->
{% endblock %}

shop/templates/shop/order_detail.html
{% extends "shop/base_generic.html" %}

{% block content %}
<h1>Order: {{order.pk}}</h1>
<ul class='data-list'>
{% for o in order.orderedproducts_set.all %}
    <li>
        <a href="{% url 'shop:product_detail' o.product.pk %}">{{ o.product.name | title}}</a> 
        - {{ o.price }} Qty. {{o.quantity}}
    </li>
{% endfor %}
</ul>

{% endblock %}

shop/templates/shop/orders.html
{% extends "shop/base_generic.html" %}

{% block content %}

<h1>Orders<b id="cart"></b></h1>
<ul class='data-list'>
{% for order in object_list %}
    <li>
        Order ID: <a href="{% url 'shop:order_detail' order.pk %}">{{order.pk}}</a>
        - {{ order.date }}
    </li>
{% empty %}
    <li>You have not made any orders yet</li>
{% endfor %}
</ul>


{% endblock %}

shop/templates/shop/product_detail.html
{% extends "shop/base_generic.html" %}

{% block content %}
<div id="path">
    <a href="{%url 'shop:index'%}"> Home </a>
    {% for cat in product.category.get_parents %}
    > <a href="{% url 'shop:category_detail' cat.pk %}">{{cat}}</a>
    {% endfor %}
    >  <a href="{% url 'shop:product_detail' product.pk %}">{{product.name}}</a>
    </div>
<h1 id="name">{{product.name | title}}</h1>
<h3>Price: {{ product.price }}</h3>
{% if product.quantity > 0 %}
<h3>In stock: {{ product.quantity }}</h3>
{% else %}
<h3>Out of stock</h3>
{% endif %}

{% if user.is_authenticated %}
<b class="hidden" id="pk">{{product.pk}}</b>
<br><br>
<label for="quantity">Quantity:</label>
<br>
<input type="number" step="1" id="quantity" min="0" size="2" max="{{ product.quantity }}">
<br><br>
<button id="addCart">Add to cart</button>

{% endif %}

{% endblock %}

shop/templates/shop/products.html
{% extends "shop/base_generic.html" %}

{% block content %}

<h1>Products</h1>
<ul class='data-list'>
{% for product in object_list %}
    <li>
        <a href="{% url 'shop:product_detail' product.pk %}">{{ product.name | title}}</a> 
        - {{ product.price }}
    </li>
{% empty %}
    <li>We're not selling stuff yet.</li>
{% endfor %}
</ul>

{% endblock %}